NuochoaHuxtah/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuochoaHuxtah.Models;
using NuochoaHuxtah.Repository;

namespace NuochoaHuxtah.Controllers
{
	public class BrandController : Controller
	{
		private readonly DataContext _dataContext;
		public BrandController(DataContext context)
		{
			_dataContext = context;
		}
		public async Task<IActionResult> Index(string Slug = "")
		{
			BrandModel brand = _dataContext.Brands.Where(p => p.Slug == Slug).FirstOrDefault();
			if (brand == null) // Nếu brand không có thì trả về trang index
			{
				return RedirectToAction("Index");
			}
			var productsByCategory = _dataContext.Products.Where(p => p.BrandId == brand.Id); // Điều kiện brandid phải bằng brand.id
			return View(await productsByCategory.OrderByDescending(p => p.Id).ToListAsync());// OrderByDescending() : Giống LIFO(stack)
		}
	}
}

NuochoaHuxtah/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuochoaHuxtah.Models;
using NuochoaHuxtah.Repository;

namespace NuochoaHuxtah.Controllers
{
    public class CategoryController : Controller
    {
        private readonly DataContext _dataContext;
        public CategoryController(DataContext context)
        {
            _dataContext = context;
        }
        
        public async Task<IActionResult> Index(string Slug="")
        {
            CategoryModel category = _dataContext.Categories.Where(p => p.Slug == Slug).FirstOrDefault();
            if (category == null)
            {
                return RedirectToAction("Index");
            }
            var productsByCategory = _dataContext.Products.Where(p => p.CategoryId == category.Id);
            return View(await productsByCategory.OrderByDescending(p => p.Id).ToListAsync());
        }
    }
}

NuochoaHuxtah/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuochoaHuxtah.Models;
using NuochoaHuxtah.Models.ViewModels;
using NuochoaHuxtah.Repository;

namespace NuochoaHuxtah.Controllers
{
	public class ProductController : Controller
    {
		private readonly DataContext _dataContext;
		public ProductController(DataContext context)
		{
			_dataContext = context;
		}
		public IActionResult Index()
        {
            return View();
        }
        public async  Task<IActionResult> Details( int Id )
        {
            if(Id ==null)
            {
                return RedirectToAction("Index");
            }
			var productsById = _dataContext.Products
                .Include(p=>p.Reviews)
                .Where(p => p.Id == Id).FirstOrDefault();

            var relatedProducts = await _dataContext.Products
                .Where(p=>p.CategoryId == productsById.CategoryId && p.Id != productsById.Id)
                .Take(4)
                .ToListAsync();
            
            ViewBag.RelatedProducts = relatedProducts;
            var viewModel = new ProductDetailsViewModel
            {
                ProductDetails = productsById,
                
            };
			return View(viewModel);
        }
        public async Task<IActionResult> CommentProduct(ReviewModel review)
        {
            if(ModelState.IsValid)
            {
                var reviewEntity = new ReviewModel
                {
                    ProductId = review.ProductId,
                    Name = review.Name,
                    Email = review.Email,
                    Comment = review.Comment,
                    Rating = review.Rating

                };

                _dataContext.Reviews.Add(reviewEntity);
                await _dataContext.SaveChangesAsync();
                TempData["success"] = "Thêm đánh giá thành công";
                return Redirect(Request.Headers["Referer"]);


            }
            else
            {
				TempData["error"] = "Model not ok";
				List<string> errors = new List<string>();
				foreach (var value in ModelState.Values)
				{
					foreach (var error in value.Errors)
					{
						Console.WriteLine(error.ErrorMessage);
						errors.Add(error.ErrorMessage);
						
					}
				}
				string errorMessage = string.Join("\n", errors);
				return RedirectToAction("Details", new {id = review.ProductId});
            }
            return Redirect(Request.Headers["Referer"]);
        }
        // Tìm theo từ khóa
        public async Task<IActionResult> Search(string searchTerm)
        {
            var products = await _dataContext.Products.Where(p => p.Name.Contains(searchTerm) || p.Description.Contains(searchTerm)).ToListAsync();
            ViewBag.Keyword = searchTerm;
            return View(products);   
        }
    }
}

NuochoaHuxtah/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewData["title"] - Admin | Nước hoa Huxtah</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/css/prettyPhoto.css" rel="stylesheet">
    <link href="~/css/price-range.css" rel="stylesheet">
    <link href="~/css/animate.css" rel="stylesheet">
    <link href="~/css/main.css" rel="stylesheet">
    <link href="~/css/responsive.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.14.1/dist/sweetalert2.min.css" rel="stylesheet">
    
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <link href="//cdn.datatables.net/2.1.7/css/dataTables.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/3.1.2/css/buttons.dataTables.css" rel="stylesheet">
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
    <header id="header">
        <!--header-->
        <div class="header_top">
            <!--header_top-->
            <div class="container">
                <div class="row">
                </div>
            </div>
        </div><!--/header_top-->

        <div class="header-middle">
            <!--header-middle-->
            <div class="container">
                <div class="row">
                </div>
            </div>
        </div><!--/header-middle-->

        <div class="header-bottom">
            <!--header-bottom-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-9">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="mainmenu pull-left">
                            <ul class="nav navbar-nav collapse navbar-collapse">
                                
                                <li><a asp-action="Index" asp-controller="Product">Quản lý sản phẩm</a></li>
                                <li><a asp-action="Index" asp-controller="Category">Quản lý danh mục</a></li>
                                <li><a asp-action="Index" asp-controller="Brand">Quản lý thương hiệu</a></li>
                                <li><a asp-action="Index" asp-controller="Order">Quản lý đơn hàng</a></li>
                                <li><a asp-action="Index" asp-controller="User">Quản lý người dùng</a></li>
                                <li><a asp-action="Index" asp-controller="Role">Quản lý quyền</a></li>
                                <li><a asp-action="Index" asp-controller="Home">Trang chủ</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="search_box pull-right">
                            <input type="text" placeholder="Search" />
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header-bottom-->
    </header><!--/header-->

    <section>
        <div class="container">
            <div class="row">
                @Html.Partial("_NotificationPatial")
                @RenderBody()
            </div>
        </div>
    </section>

    <footer id="footer">
        <!--Footer-->

    </footer><!--/Footer-->



    <script src="~/js/jquery.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.scrollUp.min.js"></script>
    <script src="~/js/price-range.js"></script>
    <script src="//cdn.datatables.net/2.1.7/js/dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/dataTables.buttons.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/buttons.dataTables.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/buttons.html5.min.js"></script>
    <script src="~/js/jquery.prettyPhoto.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/backend/js/site.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.14.1/dist/sweetalert2.all.min.js"></script>
    

    <script>
        $(function () {
            var message = '@TempData["success"]';
            if (message != '')
                Swal.fire(message);
        });
            
    </script>
    
    <script>
        let table = new DataTable('#mytable', {
            layout: {
                topStart: {
                    buttons: ['copyHtml5', 'excelHtml5', 'csvHtml5', 'pdfHtml5']
                }
            }
            });

    </script>
   
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NuochoaHuxtah/Areas/Admin/Views/Shared/_NotificationPatial.cshtml
@if(TempData["success"]!= null){
    <div class="alert alert-success notificaiton">
        @TempData["success"]
    </div>
}
@if(TempData["error"]!= null){
    <div class="alert alert-danger notification">
        @TempData["error"]
    </div>
}

NuochoaHuxtah/Areas/Admin/Views/Shared/_SidebarPartial.cshtml
<div class="left-sidebar">
	<h2>Danh mục</h2>
	<div class="panel-group category-products" id="accordian">
		<!--category-productsr-->

		<vc:categories></vc:categories>

	</div><!--/category-products-->
	<h2>Thương hiệu</h2>
	<div class="panel-group category-products" id="accordian">
		<!--category-productsr-->

		<vc:brands></vc:brands>

	</div><!--/category-products-->

</div>